/*jshint evil: true */
(function () {
	"use strict";

	var less = require("less"),
		path = require("path"),
		fs = require("fs"),
		mkpath = require("mkpath"),
		lessOptionKeys;

	lessOptionKeys = {
		parser: ["optimization", "filename", "strictImports", "syncImport", "dumpLineNumbers", "relativeUrls", "rootpath"],
		render: ["compress", "cleancss", "ieCompat", "strictMath", "strictUnits", "sourceMap", "sourceMapURL", "sourceMapBasepath", "sourceMapRootpath", "outputSourceFiles"]
	};

	function readOptions(input) {
		var options = {};
		input.split(",").forEach(function (item) {
			var key, value, i = item.indexOf(":");
			if (i < 0) {
				return;
			}
			key = item.substr(0, i).trim();
			value = item.substr(i + 1).trim();
			if (value.match(/^(true|false|undefined|null|[0-9]+)$/)) {
				value = eval(value);
			}
			options[key] = value;
		});
		return options;
	}

	function pick(options, keys) {
		var out = {};
		keys.forEach(function (key) {
			if (options[key]) {
				out[key] = options[key];
			}
		});
		return out;
	}

	// read less input
	function readLessFile(lessFile, callback) {
		fs.readFile(lessFile, function (err, data) {
			if (err) {
				callback(err);
				return;
			}

			var content = data.toString(),
				result = { "content": content },
				match = /^\s*\/\/\s*(.+)/.exec(content);

			if (match) {
				result.options = readOptions(match[1]);
			} else {
				result.options = {};
			}
			callback(null, result);
		});

	}

	// makes a file in a path where directories may or may not have existed before
	function mkfile(filepath, content, callback) {
		mkpath(path.dirname(filepath), function (err) {
			if (err) {
				callback(err);
			} else {
				fs.writeFile(filepath, content, callback);
			}
		});
	}

	// compile the given less file
	function compile(lessFile, callback) {

		// read the less file, returns object with the following keys:
		// - content: content of the file
		// - out: override output filename (optional)
		// - main: override compile file (optional)
		// - options: compiler options (optional)
		readLessFile(lessFile, function (err, result) {
			if (err) {
				callback(err);
				return;
			}

			// compile a different file instead
			if (result.options.main) {
				compile(path.join(path.dirname(lessFile), result.options.main), callback);
				return;
			}

			// determine output filename
			var parser, parserOptions, cssFile, sourceMapFilename, lessPath = path.dirname(lessFile);
			if (result.options.out) {
				cssFile = path.resolve(lessPath, result.options.out);
				if (path.extname(cssFile) === "") {
					cssFile += ".css";
				}
			} else {
				cssFile = lessFile.substr(0, lessFile.length - 5) + ".css";
			}

			// source map file
			if (result.options.sourceMapFilename) {
				sourceMapFilename = path.resolve(lessPath, result.options.sourceMapFilename);
				if (sourceMapFilename === cssFile) {
					sourceMapFilename += ".map";
				}
			} else {
				sourceMapFilename = cssFile + ".map";
			}

			// create less parser
			parserOptions = pick(result.options, lessOptionKeys.parser);
			parserOptions.paths = [lessPath];
			parserOptions.filename = path.basename(lessFile);
			console.log(parserOptions);
			parser = new less.Parser(parserOptions);

			// parse the file
			parser.parse(result.content, function (err, tree) {
				if (err) {
					callback(err);
					return;
				}

				var output = result.options.compress ? "" : "/* Generated by less " + less.version.join(".") + " */\n",
					renderOptions = pick(result.options, lessOptionKeys.render),
					appendToOutput = "";
				renderOptions.writeSourceMap = function (sourceMap) {
					var relativePath = path.relative(path.dirname(cssFile), sourceMapFilename);
					appendToOutput = "/*# sourceMappingURL=" + relativePath + " */";
					mkfile(sourceMapFilename, sourceMap, function (err) {
						if (err) {
							console.error(err);
						}
					});
				};
				try {
					output += tree.toCSS(renderOptions);
				} catch (err) {
					callback(err);
					return;
				}

				// write css output
				output += appendToOutput;
				mkfile(cssFile, output, function (err) {
					if (err) {
						callback(err);
					} else {
						callback(null, { filepath: cssFile, output: output });
					}
				});
			});
		});
	}

	// set up service for brackets
	function init(DomainManager) {
		if (!DomainManager.hasDomain("LessCompiler")) {
			DomainManager.registerDomain("LessCompiler", {
				major: 1,
				minor: 0
			});
		}
		DomainManager.registerCommand(
			"LessCompiler", // domain name
			"compile", // command name
			compile, // command handler function
			true, // this command is asynchronous
			"Compiles a less file", ["lessPath"], // path parameters
			null);
	}

	exports.init = init;

}());
